const OBRAS = [
  {
    id: "nori-minimum-house",
    nombre: "Minimum House",
    autor: "Nori Architects",
    estado: "Construido",
    uso: "Casa unifamiliar",
    pais: "Japón",
    ciudad: "Toyota",
    decada: "2020s",
    anio: "2022",
    fotografo: ["Jumpei Suzuki"],
    complejidad: "Nivel 2",
    url: "https://revistaplot.com/casa-minima-en-toyota/",
    cover: "https://drive.google.com/thumbnail?id=15wqG3M3k8AF7wHgT2knFyCYSxfXl1bRj&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=1abTM8TXoCnsEcl0wZjVFirCNkfLFItPq&sz=w1600", escala: 1, tipografica: [], tipoespacial: [], materiales: [], componentes: ["Cubierta", "Revestimiento", "Estructura"], extra: ["Contexto urbano", "Envolvente translúcida", "Parcela estrecha"] },
      { src: "https://drive.google.com/thumbnail?id=15wqG3M3k8AF7wHgT2knFyCYSxfXl1bRj&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Madera maciza"], componentes: ["Estructura", "Muro translucido", "Carpinteria"], extra: ["Patio", "Cerramiento translucido", "Estructura de madera"] },
      { src: "https://drive.google.com/thumbnail?id=1s3aRM1Ka-Yp4t2Zz8yuRRo1xpEflvZ6m&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Acero"], componentes: ["Piso", "Muro translucido", "Barandilla"], extra: ["Piso de rejilla", "Cerramiento ligero", "Filtro visual"] },
      { src: "https://drive.google.com/thumbnail?id=1jXLgj9qPrIDZzvOgrQ8UDCsVZI2_ZQ3O&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Madera maciza", "Policarbonato"], componentes: ["Estructura", "Cubierta", "Cerco"], extra: ["Estructura de madera", "Cerramiento ligero", "Balcon enrejado"] },
      { src: "https://drive.google.com/thumbnail?id=1TQAhTc0fuwy_iGlDiUcBkcxMaxGVZcLM&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Madera maciza"], componentes: ["Estructura", "Revestimiento", "Cubierta"], extra: ["malla metalica", "estructura vista", "habitacion exterior"] },
      { src: "https://drive.google.com/thumbnail?id=1_mKRHcSMylYN4zkUjBQeJIB2Jg3fcxjf&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Patio"], materiales: ["Madera maciza", "Acero"], componentes: ["Estructura", "Muro translucido", "Carpinteria"], extra: ["estructura expuesta", "malla metalica", "celosia exterior"] },
      { src: "https://drive.google.com/thumbnail?id=1U7Vk0WcMy717zspdMyLciaVBVaIcSylV&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Estar", "Comedor"], materiales: ["Madera laminada"], componentes: ["Escalera", "Carpinteria", "Estructura"], extra: ["doble altura", "estructura vista", "entrepiso"] },
      { src: "https://drive.google.com/thumbnail?id=1ypWg5ZGKsw7jq_THj-yIjvdbegSMCHR0&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Comedor", "Cocina"], materiales: ["Madera maciza"], componentes: ["Estructura", "Escalera", "Muro opaco"], extra: ["doble altura", "mezaninas", "estructura vista"] },
      { src: "https://drive.google.com/thumbnail?id=19DI3Avhp9tMbrScM3_S9G6s_7OwzWbSf&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Estar"], materiales: ["Madera laminada"], componentes: ["Escalera", "Estructura", "Muro transparente"], extra: ["Estructura de madera vista", "Luz tamizada", "Plywood interior"] },
      { src: "https://drive.google.com/thumbnail?id=1tEDzu12xpR5DE9WCS3NoLU29p8saPaV4&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Estar"], materiales: ["Madera laminada"], componentes: ["Escalera", "Muro opaco", "Cielorraso"], extra: ["estructura de madera", "contrachapado", "ducto visto"] },
      { src: "https://drive.google.com/thumbnail?id=16R-U2RUPJcEwmITHfXQ_g45L6UXjfO-X&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Estar"], materiales: ["Madera laminada"], componentes: ["Escalera", "Muro opaco", "Cielorraso"], extra: ["estructura vista", "luz natural difusa", "paneles madera"] },
      { src: "https://drive.google.com/thumbnail?id=1vIe-zCRpSyTxXjjv9HOPiOk7wJAbKF8_&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Estar"], materiales: ["Madera maciza"], componentes: ["Carpinteria", "Muro transparente", "Muro opaco"], extra: ["Estructura vista", "Ventanal esquina", "Luminosidad interior"] },
      { src: "https://drive.google.com/thumbnail?id=1utmiIk5sWqhF1xBIstnOK9N_TuBGzqOx&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Comedor", "Cocina"], materiales: ["Madera laminada"], componentes: ["Muro opaco", "Carpinteria", "Iluminacion"], extra: ["Estructura vista", "Interiorismo madera", "Luz natural"] },
      { src: "https://drive.google.com/thumbnail?id=12vhAaBMmRqX92kRAevlvEYEvhrTAm7kf&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Comedor", "Cocina"], materiales: ["Madera laminada"], componentes: ["Estructura", "Escalera", "Carpinteria"], extra: ["Estructura de madera", "Luz natural", "Espacio diáfano"] },
      { src: "https://drive.google.com/thumbnail?id=11MclllvUb58m79neO0VFxShDsBm3cZU3&sz=w1600", escala: 9, tipografica: ["Planta"], tipoespacial: [], materiales: [], componentes: ["Muro opaco", "Carpinteria", "Escalera"], extra: ["Planta baja", "Distribucion", "Vivienda unifamiliar"] },
      { src: "https://drive.google.com/thumbnail?id=1qqUpniP37xeR113Ff7kgjhFGpXFxlyZl&sz=w1600", escala: 9, tipografica: ["Planta"], tipoespacial: [], materiales: [], componentes: [], extra: ["planta arquitectonica", "distribucion interior", "escalera"] },
      { src: "https://drive.google.com/thumbnail?id=1HPSH3NogGKMmIe1La2QYEbyj6HO42ZnV&sz=w1600", escala: 9, tipografica: ["Planta"], tipoespacial: [], materiales: [], componentes: [], extra: ["Vivienda unifamiliar", "Distribucion interior", "Estacionamiento"] },
      { src: "https://drive.google.com/thumbnail?id=1nL2nxWDN0uamKG9WvIpYJSjeoLWN-jsz&sz=w1600", escala: 10, tipografica: ["Corte", "Esquema"], tipoespacial: [], materiales: [], componentes: ["Estructura", "Muro transparente", "Escalera"], extra: ["ventilacion natural", "iluminacion natural", "diagrama funcional"] },
      { src: "https://drive.google.com/thumbnail?id=1PcZpbvMDVc1k2t660Vx5xz1WzETJpmTt&sz=w1600", escala: 12, tipografica: ["Axonometria", "Despiece"], tipoespacial: [], materiales: [], componentes: ["Estructura", "Cubierta", "Muro opaco"], extra: ["sistema constructivo", "ensamblaje", "prefabricacion"] }
    ]
  },
  {
    id: "casa-ma-sant-cugat",
    nombre: "Casa MA",
    autor: "bxd arquitectura + Cra-De.studio",
    estado: "Construido",
    uso: "Casa unifamiliar",
    pais: "España",
    ciudad: "Sant Cugat del Vallès",
    decada: "2020s",
    anio: "2023",
    fotografo: "Aleix Bagué",
    complejidad: "Nivel 2",
    url: "https://arquitecturaviva.com/works/casa-ma-en-sant-cugat-de-valles-barcelona",
    cover: "https://drive.google.com/thumbnail?id=1lh82zKcpz2GxWAdvHLaEa8pCbolU6n8r&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=1P8r637bD-SIG7bz_CzsOl4KucuqjixCh&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Madera maciza"], componentes: ["Carpinteria", "Parasol", "Piso"], extra: ["Luz y sombra", "Lamas verticales", "Filtro visual"] },
      { src: "https://drive.google.com/thumbnail?id=1JEfH1xhpmgrHlds1bV_hW5okFIgCT3X7&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Madera maciza"], componentes: ["Piso", "Barandilla", "Parasol"], extra: ["Decking", "Lamas", "Sol y sombra"] },
      { src: "https://drive.google.com/thumbnail?id=1Zb4PrEhqmsWxP8m8oOPS-3HnOpKY1inY&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Madera maciza"], componentes: ["Piso", "Parasol", "Barandilla"], extra: ["Luz y sombra", "Celosia vertical", "Control solar"] },
      { src: "https://drive.google.com/thumbnail?id=1nQ0Ojc8kaEQWF1CXXMfZVItv-l68kP0G&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Vereda"], materiales: [], componentes: ["Estructura", "Barandilla", "Parasol"], extra: ["fachada modular", "parasoles enrollables", "bloques de vidrio"] },
      { src: "https://drive.google.com/thumbnail?id=1DYCQH4dtj70SAGB0KOYzO2Bm9FwYIQso&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Aluminio"], componentes: ["Barandilla", "Parasol", "Cerco"], extra: ["Fachada modulada", "Balcones", "Protección solar"] },
      { src: "https://drive.google.com/thumbnail?id=17-_-5y094hrhqimYFtl2K5MiPcfAqEJR&sz=w1600", escala: 3, tipografica: [], tipoespacial: [], materiales: [], componentes: ["Parasol", "Barandilla", "Carpinteria"], extra: ["Lamas verticales", "Balcones", "Modulacion"] },
      { src: "https://drive.google.com/thumbnail?id=1rk6b_eJDHe5DMFETJ4SF95ALHzrG08k5&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Vereda"], materiales: ["Aluminio"], componentes: ["Cerco", "Estructura", "Parasol"], extra: ["celosía vertical", "estructura modular", "balcones"] },
      { src: "https://drive.google.com/thumbnail?id=1lrpbk98u2RTEN2PX6ehEJmGr8uVeM8xL&sz=w1600", escala: 3, tipografica: [], tipoespacial: [], materiales: ["Aluminio"], componentes: ["Estructura", "Parasol", "Barandilla"], extra: ["proteccion solar", "modulacion fachada", "balcones"] },
      { src: "https://drive.google.com/thumbnail?id=1HyONmP0MYgoJmyKYpBgAD2X9cryOi_nm&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Terraza"], materiales: [], componentes: ["Barandilla", "Persiana", "Cerco"], extra: ["Fachada reticular", "Balcones apilados", "Proteccion solar"] },
      { src: "https://drive.google.com/thumbnail?id=1lh82zKcpz2GxWAdvHLaEa8pCbolU6n8r&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Terraza"], materiales: ["Madera maciza"], componentes: ["Parasol", "Carpinteria", "Piso"], extra: ["lamas verticales", "sombras proyectadas", "conexión exterior"] },
      { src: "https://drive.google.com/thumbnail?id=1lx2Ovgo3b_XsWH_egzqW-aPUTmtl1N70&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Cocina"], materiales: ["Madera maciza"], componentes: ["Carpinteria", "Piso", "Barandilla"], extra: ["Iluminacion natural", "Integracion", "Minimalismo"] },
      { src: "https://drive.google.com/thumbnail?id=1h7wX9E0HP8mn21Xm0FKIsMeAmnudzigC&sz=w1600", escala: 9, tipografica: ["Planta"], tipoespacial: [], materiales: [], componentes: [], extra: ["esquema", "comparativa", "reorganizacion"] },
      { src: "https://drive.google.com/thumbnail?id=1wdJ4CnVWVU1gpBUcAkSsOzIkvva6pkJk&sz=w1600", escala: 10, tipografica: ["Corte"], tipoespacial: [], materiales: [], componentes: ["Cubierta", "Entrepiso", "Parasol"], extra: ["Cubierta verde", "Subsuelo", "Sustentabilidad"] },
      { src: "https://drive.google.com/thumbnail?id=1tv-MNY1yFADJTu0G5Vcl8ILO_FJ_knRV&sz=w1600", escala: 12, tipografica: ["Axonometria"], tipoespacial: [], materiales: [], componentes: ["Estructura", "Muro transparente", "Escalera"], extra: ["axonometria explotada", "modulacion", "sistema constructivo"] }
    ]
  },
  {
    id: "aeg-national-headquarters",
    nombre: "AEG National Headquarters",
    autor: "BNIM",
    estado: "Restaurado",
    uso: "Edificio de oficinas",
    pais: "USA",
    ciudad: "Des Moines",
    decada: "2010s",
    anio: "2016",
    fotografo: "Chad Davies",
    complejidad: "Nivel 4",
    url: "https://www.archdaily.com/783730/american-enterprise-group-national-headquarters-renovation-bnim",
    cover: "https://drive.google.com/thumbnail?id=1-0dfFFX6kLowm5gvurNugnwsuczWgvxn&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=1tPOkoON4H68XO3gZGyRpMhtfUFWdURCd&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Plaza"], materiales: ["Acero"], componentes: ["Cielorraso"], extra: ["entrada principal", "escultura esferica", "iluminacion cenital"] },
      { src: "https://drive.google.com/thumbnail?id=1fVAEJ7k5lN7rQWp-PqMWYxTFwNrdr-E2&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Lobby"], materiales: ["Hormigon"], componentes: ["Muro transparente"], extra: ["atrio", "iluminación artificial", "perspectiva cenital"] },
      { src: "https://drive.google.com/thumbnail?id=1gwPqJpko-GEWZiFFy8d4Li-BBoNc7y5d&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Oficina"], materiales: ["Hormigon", "Vidrio"], componentes: ["Estructura", "Muro transparente", "Iluminacion"], extra: ["Fachada modular", "Iluminacion nocturna", "Retícula estructural"] },
      { src: "https://drive.google.com/thumbnail?id=13HYTzlI0xOsii9ClDN3gn_x8hJOWeTtT&sz=w1600", escala: 3, tipografica: [], tipoespacial: [], materiales: ["Hormigon"], componentes: ["Estructura"], extra: ["bandas horizontales", "voladizos", "fachada modular"] },
      { src: "https://drive.google.com/thumbnail?id=1bVsy3LBOSUFCTLJjlKf7rjRxCArZp2nQ&sz=w1600", escala: 3, tipografica: [], tipoespacial: [], materiales: ["Hormigon"], componentes: ["Parasol"], extra: ["Brutalismo", "Modulo repetitivo", "Encofrado a la vista"] },
      { src: "https://drive.google.com/thumbnail?id=16YDauUAx83LDUxSNBNmooB3LAi509tBo&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"], materiales: ["Vidrio", "Acero"], componentes: ["Iluminacion", "Panel"], extra: ["Mobiliario de diseno", "Espacio lineal", "Iluminacion ritmica"] },
      { src: "https://drive.google.com/thumbnail?id=11eqDaV3UnlvNjl83wgPvqw5-fxp0PUy1&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"], materiales: ["Vidrio", "Marmol"], componentes: ["Cielorraso", "Muro transparente"], extra: ["techo reticular", "divisiones de vidrio", "corredor oficinas"] },
      { src: "https://drive.google.com/thumbnail?id=1mwju63B4lFaURDC_pl80dKowcqxFisuH&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Oficina"], materiales: ["Madera laminada"], componentes: ["Persiana"], extra: ["Oficina ejecutiva", "Vista urbana", "Mobiliario moderno"] },
      { src: "https://drive.google.com/thumbnail?id=1ThfCh9hu9GPhqpFFr7y9oG8MMvOIJUYs&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Lobby"], materiales: [], componentes: ["Cielorraso"], extra: ["Ductos vistos", "Vigas expuestas", "Sillas Barcelona"] },
      { src: "https://drive.google.com/thumbnail?id=1zh87gkN4Iw8lYok7FB7iPM3ghw8MC9dg&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"], materiales: ["Hormigon"], componentes: ["Iluminacion"], extra: ["Atrio", "Retícula", "Luz artificial"] },
      { src: "https://drive.google.com/thumbnail?id=1xTK7D_ipRYWUIOBc_uBY1u3zasjwvOIY&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"], materiales: [], componentes: [], extra: ["Corredor", "Iluminación empotrada", "Arte gráfico"] },
      { src: "https://drive.google.com/thumbnail?id=1nCjSAx15e-k1c-Po3DdnO4MSgyw-9f5y&sz=w1600", escala: 9, tipografica: ["Planta"], tipoespacial: [], materiales: [], componentes: [], extra: ["planta baja", "reconfiguracion", "cambio de uso"] },
      { src: "https://drive.google.com/thumbnail?id=1uKHk6SxDtHn74Gi4WYtWrm9mJp5_jShN&sz=w1600", escala: 9, tipografica: ["Planta"], tipoespacial: [], materiales: [], componentes: [], extra: ["evolución planimétrica", "remodelación", "distribución interna"] },
      { src: "https://drive.google.com/thumbnail?id=1dkUigaqYli77zu5tKenEq7UVwfFFGqQA&sz=w1600", escala: 10, tipografica: ["Corte"], tipoespacial: [], materiales: [], componentes: ["Estructura", "Entrepiso", "Parasol"], extra: ["corte longitudinal", "fachada modular", "voladizos"] }
    ]
  },
  {
    id: "casa-del-mordisco",
    nombre: "Casa del Mordisco",
    autor: "BIOMA",
    estado: "Construido",
    uso: "Casa unifamiliar",
    pais: "Argentina",
    ciudad: "Balcarce",
    decada: "2020s",
    anio: "2023",
    fotografo: "Javier Agustín Rojas",
    complejidad: "Nivel 2",
    url: "https://www.archdaily.cl/cl/1038841/casa-del-mordisco-bioma",
    cover: "https://drive.google.com/thumbnail?id=1hUS70j4B4VyAFNqaLIFyLX0MV4iPZsLp&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=1hvo3ZJh5QZ_V5pdl7wmWemMT9J1XRsid&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Galeria"], materiales: ["Madera laminada"], componentes: ["Carpinteria"], extra: ["Mobiliario integrado", "Hormigon visto", "Luz difusa"] }
,
      { src: "https://drive.google.com/thumbnail?id=1hUS70j4B4VyAFNqaLIFyLX0MV4iPZsLp&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Jardin"], materiales: [], componentes: ["Cubierta"], extra: ["Cubierta ondulada", "Integración paisajística", "Grandes ventanales"] }
,
      { src: "https://drive.google.com/thumbnail?id=1BHToHidDDJwfA59AAp6RermROZ4Li2Sd&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Jardin"], materiales: [], componentes: ["Cubierta"], extra: ["Cubierta ondulada", "Paisaje rural", "Piscina exterior"] }
,
      { src: "https://drive.google.com/thumbnail?id=13aXXrOJOrUdQxDWHGuFL15fRbBnBx7aT&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Jardin"], materiales: [], componentes: [], extra: ["Atardecer", "Voladizo", "Paisaje natural"] }
,
      { src: "https://drive.google.com/thumbnail?id=1PwYVpSzlHGpaQ-VUCxBEqrswHh4tXBvy&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Jardin"], materiales: [], componentes: ["Cubierta"], extra: ["Cubierta ondulada", "Paisaje natural", "Volumetria longitudinal"] }
,
      { src: "https://drive.google.com/thumbnail?id=1nZw10WaGqxsdUEDGVCzqytHI7sPjKoI0&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Jardin"], materiales: [], componentes: ["Cubierta"], extra: ["cubierta ondulada", "integracion paisajistica", "arquitectura organica"] }
,
      { src: "https://drive.google.com/thumbnail?id=1Pe_pfSMqF_zQQrXbn8gEjD7LJNWXDM2Z&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Jardin"], materiales: ["Hormigon"], componentes: ["Cubierta"], extra: ["bovedas", "luz difusa", "entorno natural"] }
,
      { src: "https://drive.google.com/thumbnail?id=1M03lWJw05hY6fChBpcdCJ7Qdt5u7oRuS&sz=w1600", escala: 3, tipografica: [], tipoespacial: ["Jardin"], materiales: [], componentes: ["Cubierta"], extra: ["Cubierta ondulada", "Integracion paisajistica", "Luz artificial"] }
,
      { src: "https://drive.google.com/thumbnail?id=17xlBcmhwO7Ivau-c3oOUQ5ZhWBqktbvU&sz=w1600", escala: 3, tipografica: [], tipoespacial: [], materiales: [], componentes: [], extra: ["Casa en bosque", "Cubierta ondulada", "Iluminacion nocturna"] }
,
      { src: "https://drive.google.com/thumbnail?id=1nKcineMHRoAmOmzkIU1Fmo2T-HU5PaHJ&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Oficina"], materiales: ["Madera maciza"], componentes: ["Muro transparente", "Carpinteria"], extra: ["cubierta curva", "vista panoramica", "mobiliario integrado"] }
,
      { src: "https://drive.google.com/thumbnail?id=1L7o5IEq19VR_S80C4wE5BoR_EvUqUkTH&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Comedor"], materiales: ["Vidrio"], componentes: ["Muro transparente"], extra: ["Boveda", "Planta libre", "Conexion exterior"] }
,
      { src: "https://drive.google.com/thumbnail?id=1Yr57Z9wJdtk2wudX9BKP3qOkaS7zL7iT&sz=w1600", escala: 4, tipografica: [], tipoespacial: ["Cocina"], materiales: ["Hormigon"], componentes: ["Cielorraso", "Muro transparente"], extra: ["vista panoramica", "boveda", "espacio diafano"] }
    ]
  },
  {
    id: "st-catherines-college",
    nombre: "St Catherine's College",
    autor: "Arne Jacobsen",
    estado: "Construido",
    uso: "Universidad",
    pais: "UK",
    ciudad: "Oxford",
    decada: "1960s",
    anio: "1964",
    fotografo: "Sin crédito",
    complejidad: "Nivel 4",
    url: "https://arnejacobsen.com/works/st-catherines-college-2/",
    cover: "https://drive.google.com/thumbnail?id=1V1GOLP-qf8vk01Q3m5nelP90d7jd_0nv&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=1y9nP8Z50qOCCu5k9YrWbISXh9F3JJ2zI&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Dormitorio"],
        materiales: ["Madera maciza", "Yeso"], componentes: ["Muro opaco", "Cielorraso", "Piso", "Iluminacion", "Puerta", "Carpinteria", "Panel"], extra: ["Mobiliario integrado", "Diseño modular", "Estudio universitario"] },
      { src: "https://drive.google.com/thumbnail?id=17zyEt4rzZ9H9AxcOPLrOwsPqijUQ6iMc&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Vereda"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio", "Baldosa"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Parasol", "Piso", "Revestimiento", "Iluminacion"], extra: ["brutalismo", "modulacion", "fachada ritmica"] },
      { src: "https://drive.google.com/thumbnail?id=1RlunexPBrea9C9-x7Gom438psmuMa6FC&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Acero"], componentes: ["Estructura", "Barandilla"], extra: ["Campanario", "Brutalismo", "Celosia metalica"] },
      { src: "https://drive.google.com/thumbnail?id=1yJsNsciHqtDa6BySfpmXd6_gBwxLtW5a&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin", "Galeria"],
        materiales: ["Hormigon", "Ladrillo"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Parasol"], extra: ["Brutalismo", "Torre campanario", "Columnata"] },
      { src: "https://drive.google.com/thumbnail?id=1OMwkS6c_JiKU2B8Tj7Vn4yMInacINo1K&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio", "Ladrillo"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Cielorraso", "Piso", "Iluminacion", "Estructura", "Revestimiento"], extra: ["Cantilever", "Modulacion", "Brutalismo"] },
      { src: "https://drive.google.com/thumbnail?id=1gGN-wCIWc6t48fKXWsR8UhWPrRE3ujGT&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Vereda"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Estructura", "Iluminacion"], extra: ["Fachada modular", "Parasoles verticales", "Hormigon prefabricado"] },
      { src: "https://drive.google.com/thumbnail?id=1Hz3WymZHvoVVXUzwUj7nTBhYoqM_deh7&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Galeria"],
        materiales: ["Cobre", "Hormigon", "Ladrillo", "Madera maciza", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Estructura", "Cielorraso", "Piso", "Revestimiento", "Carpinteria", "Puerta", "Iluminacion", "Parasol"], extra: ["Pátina", "Voladizo", "Modulo"] },
      { src: "https://drive.google.com/thumbnail?id=1lAtdG1lMrb9KPZQwZBrGcGgr9vkKABo9&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso"], extra: ["Brutalismo", "Pilotis", "Modularidad"] },
      { src: "https://drive.google.com/thumbnail?id=1OTRyDuaPUu5tjJ6N4QMcOSpf401Wb9gP&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Parasol", "Instalacion pluvial"], extra: ["Patio ajardinado", "Fachada modular", "Brutalismo"] },
      { src: "https://drive.google.com/thumbnail?id=17wCIG1xRq9S6utEksKHQTk14-8ScDHZJ&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Ladrillo", "Vidrio", "Hormigon"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Iluminacion"], extra: ["Patio interior", "Cerramiento vidriado", "Jardinera modular"] },
      { src: "https://drive.google.com/thumbnail?id=1BAdO8KNsE74YGXNxNZkLMZOe4sCA_8nL&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Madera maciza", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Puerta", "Iluminacion", "Revestimiento"], extra: ["Fachada modular", "Patina", "Columnas de hormigón"] },
      { src: "https://drive.google.com/thumbnail?id=1IKipBcjPC3QdynZY5s5RFzbZELX5AE-S&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Aluminio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Puerta", "Cielorraso", "Iluminacion"], extra: ["Fachada modular", "Pilotis", "Lamas verticales"] },
      { src: "https://drive.google.com/thumbnail?id=1N4OJxqFhGndzOVX2HRXdOHPt1Tw6s5Hv&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Puerta", "Iluminacion"], extra: ["fachada modular", "pilares hormigon", "campus universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1JLdpQr-HD_l-E-JUvGK3nXp33HZendQn&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin", "Plaza"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Cobre"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Puerta", "Cubierta", "Instalacion pluvial"], extra: ["Fachada modular", "Brutalismo", "Pórtico"] },
      { src: "https://drive.google.com/thumbnail?id=136LqmUlB8cI4orckfdwb3tJVmDZmFjh8&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Baldosa"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Cielorraso", "Parasol"], extra: ["Brutalismo", "Campus universitario", "Patio central"] },
      { src: "https://drive.google.com/thumbnail?id=1DeeFBAcoNyaPw67JOZFjpgJ2mZz2u4he&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin", "Patio"],
        materiales: ["Hormigon", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cubierta", "Parasol", "Piso", "Carpinteria"], extra: ["Patio central", "Prefabricacion", "Columnata"] },
      { src: "https://drive.google.com/thumbnail?id=1WM_RWE-bj8XX16wiOsmZ82gjysg6IkHY&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio", "Madera maciza"], componentes: ["Muro opaco", "Cubierta", "Piso", "Carpinteria", "Puerta", "Estructura", "Iluminacion"], extra: ["Muro vegetal", "Modularidad", "Paisajismo"] },
      { src: "https://drive.google.com/thumbnail?id=1ND_xYhF5eWvlVYjdPW7ngbpgWGQ1E-ru&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Estructura", "Cubierta", "Barandilla", "Carpinteria", "Piso"], extra: ["Quadrangle", "Racionalismo", "Fachada ritmica"] },
      { src: "https://drive.google.com/thumbnail?id=17XBYIrV_33Atr33Fkg04PZhpvDvM3EXy&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Carpinteria", "Parasol"], extra: ["Brutalismo", "Fachada modular", "Colegio universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1H4ddKOqvkSpfWHOaK64PVuUGTQfCO3kQ&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Aluminio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Puerta", "Piso", "Parasol", "Iluminacion"], extra: ["Muro cortina", "Pilotis", "Fachada modular"] },
      { src: "https://drive.google.com/thumbnail?id=1mieSluC9qtTnX4czJrYpcoKBE6rIl89q&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Madera maciza", "Hormigon", "Ladrillo"], componentes: ["Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Carpinteria", "Iluminacion", "Lucarna"], extra: ["Luz cenital", "Pared inclinada", "Cielorraso acanalado"] },
      { src: "https://drive.google.com/thumbnail?id=1xPvtY-viF-ThUv1qnAA12ByJJA5NCwC0&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Ladrillo", "Vidrio", "Hormigon"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Revestimiento"], extra: ["Muro cortina", "Ladrillo horizontal", "Patio universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1btdcaTpfBageKb3HUbqeNfosbAibEp6Z&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Canaleta"], extra: ["Quadrangle", "Modulacion", "Brutalismo"] },
      { src: "https://drive.google.com/thumbnail?id=1LKrsgNw0lrfIh7UDExc3h_lS5mwRVhq7&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Bronce", "Ladrillo", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Revestimiento", "Carpinteria", "Parasol", "Piso", "Cerco"], extra: ["Modularidad", "Brutalismo", "Patina"] },
      { src: "https://drive.google.com/thumbnail?id=1Pmule0r8zyraRIVP2snueyjrWnjYfQKM&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Plaza"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Piso"], extra: ["Muro cortina", "Modulacion", "Pilares"] },
      { src: "https://drive.google.com/thumbnail?id=1tNXifT9uIuuF303DOeHfdDA2x2Lz2l58&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Puerta"], extra: ["Fachada curtain wall", "Basamento ladrillo", "Modulación regular"] },
      { src: "https://drive.google.com/thumbnail?id=1JK0M-9-U-OPXi7OsiboLh5oy7k71YydD&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin", "Patio"],
        materiales: ["Cobre", "Ladrillo", "Vidrio", "Hormigon", "Aluminio"], componentes: ["Muro opaco", "Muro transparente", "Estructura", "Carpinteria", "Piso", "Revestimiento"], extra: ["Patio universitario", "Muro cortina", "Volumen en voladizo"] },
      { src: "https://drive.google.com/thumbnail?id=11Uvwr1S6Y5SSD66iI-bXXe7Z-uiB1TaD&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Bronce"], componentes: ["Muro opaco", "Muro transparente", "Piso", "Parasol", "Cubierta", "Carpinteria", "Iluminacion", "Canaleta"], extra: ["Celosías hormigón", "Colegio universitario", "Patio central"] },
      { src: "https://drive.google.com/thumbnail?id=1SJrqklwDzrvcUIqPPGQ6_jRbbNcfj0Yr&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Cobre", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Revestimiento", "Piso", "Cubierta", "Parasol"], extra: ["Pilotis", "Patina", "Arquitectura modular"] },
      { src: "https://drive.google.com/thumbnail?id=1IMIlt9EDH8daEo0YZ15U18wt4dkXLE2L&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Puerta", "Piso", "Iluminacion", "Revestimiento"], extra: ["Volumen suspendido", "Clerestorio", "Hormigon visto"] },
      { src: "https://drive.google.com/thumbnail?id=1_JoJkDeXnv-HjwiMyvtsJMLiz5145F-r&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Cobre", "Vidrio", "Madera maciza"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Piso", "Puerta", "Revestimiento", "Cielorraso", "Parasol", "Iluminacion"], extra: ["Brutalismo", "Patina", "Cantilever"] },
      { src: "https://drive.google.com/thumbnail?id=1faeo5GHbLrMBkemqZn4HxYjhJCpsa7nY&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Estar"],
        materiales: ["Ladrillo", "Madera maciza", "Acero", "Hormigon"], componentes: ["Muro opaco", "Muro transparente", "Piso", "Iluminacion"], extra: ["Mobiliario de autor", "Diseño escandinavo", "Interiores modernistas"] },
      { src: "https://drive.google.com/thumbnail?id=1q3xVwVSoKib8ysb5ra1AuNEKMVEd2c05&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Cobre", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Iluminacion"], extra: ["Patina metalica", "Modulo prefabricado", "Colegio universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1zHTG8gHPtHLSFKD29dqFq0fxYB_N5nJ2&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Cubierta", "Piso", "Parasol"], extra: ["Brutalismo", "Modulacion", "Colegio universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1R0Z6IxHcAk5B6u7CM29pvnkUImo3B3r3&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"],
        materiales: ["Hormigon", "Vidrio", "Acero", "Madera maciza"], componentes: ["Puerta", "Muro transparente", "Piso", "Cielorraso", "Barandilla", "Carpinteria", "Iluminacion", "Senaletica"], extra: ["Continuidad interior-exterior", "Patio central", "Eje visual"] },
      { src: "https://drive.google.com/thumbnail?id=1oVzfb1mjxyP67SZp6GCGcbuGyxRcGIA2&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Cobre", "Vidrio", "Piedra"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Revestimiento"], extra: ["Brutalismo", "Claustro", "Patinado"] },
      { src: "https://drive.google.com/thumbnail?id=1UYDP5N8K-PyX_d-md0h_oFf7T5KuvaMr&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio"], componentes: ["Estructura", "Muro transparente", "Carpinteria", "Piso", "Barandilla", "Puerta", "Cielorraso", "Iluminacion", "Revestimiento"], extra: ["Fachada acristalada", "Colegio", "Integracion paisajistica"] },
      { src: "https://drive.google.com/thumbnail?id=1Tz6SW7ZKukjDFEG6TT7e-yyGRXrcRamM&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"],
        materiales: ["Hormigon", "Vidrio", "Madera maciza", "Acero"], componentes: ["Estructura", "Muro transparente", "Carpinteria", "Cielorraso", "Puerta", "Piso", "Iluminacion", "Barandilla", "Persiana"], extra: ["Brutalismo", "Pilares expuestos", "Transparencia"] },
      { src: "https://drive.google.com/thumbnail?id=1wB1rxHaUuOIp0ehtWPYX4jtWUDzo55SM&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Galeria"],
        materiales: ["Hormigon", "Vidrio", "Acero"], componentes: ["Estructura", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Puerta", "Revestimiento"], extra: ["Pilotis", "Fachada modular", "Grilla estructural"] },
      { src: "https://drive.google.com/thumbnail?id=1249eBzcqG_-k3fdY0bTjvudM_YyXLVP9&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Estructura", "Carpinteria", "Piso"], extra: ["Fachada acristalada", "Columnas expuestas", "Arquitectura moderna"] },
      { src: "https://drive.google.com/thumbnail?id=1_ezGrVlaeQuqmOFlPsa1eq0mFXHYQvRU&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio", "Acero"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Carpinteria", "Piso"], extra: ["Torre campana", "Fachada modular", "Campus"] },
      { src: "https://drive.google.com/thumbnail?id=1mTQqWQSOD-ZjYH2AYitvjEFvZOEaaEeD&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Piedra", "Vidrio", "Ladrillo"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Barandilla"], extra: ["Brutalismo", "Fachada modular", "Hormigón visto"] },
      { src: "https://drive.google.com/thumbnail?id=1YhdZICo1yWj6NXCdUzGOfAKL4S3e-bAt&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Estar"],
        materiales: ["Ladrillo", "Acero", "Vidrio", "Madera maciza", "Hormigon", "Ceramica"], componentes: ["Muro opaco", "Hogar", "Cielorraso", "Piso", "Carpinteria"], extra: ["Chimenea integrada", "Ladrillo visto", "Diseño interior"] },
      { src: "https://drive.google.com/thumbnail?id=1_yfsMvvTjFRLnXcCbgYQTFnIpqCTZ7mC&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Vereda"],
        materiales: ["Hormigon", "Vidrio", "Acero", "Ladrillo"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Parasol", "Canaleta"], extra: ["Hormigón visto", "Fachada rítmica", "Modularidad"] },
      { src: "https://drive.google.com/thumbnail?id=1j4-J7ut-JwMzNSWKEZBwyjhy_HzFnbhB&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Barandilla", "Instalacion pluvial"], extra: ["Hormigon visto", "Parasoles verticales", "Patio escalonado"] },
      { src: "https://drive.google.com/thumbnail?id=15cnRIn8y7_XFQrBZMqU6Ke4kjPQM_Vct&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio", "Ladrillo", "Acero"], componentes: ["Estructura", "Muro transparente", "Carpinteria", "Piso"], extra: ["brutalismo", "espejo de agua", "modulacion"] },
      { src: "https://drive.google.com/thumbnail?id=14XXlGpXAEFzEG4dVC92gIttevfOI9Uok&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio", "Ladrillo", "Aluminio"], componentes: ["Estructura", "Muro transparente", "Muro opaco", "Carpinteria"], extra: ["Fachada modular", "Brutalismo", "Paisaje acuático"] },
      { src: "https://drive.google.com/thumbnail?id=1pbVqUCuNh8zL0Ld1xXIpzIqbp_b2b6kd&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin", "Patio"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Estructura", "Carpinteria", "Cubierta", "Parasol", "Piso", "Barandilla"], extra: ["Reflejo agua", "Fachada modular", "Claustro"] },
      { src: "https://drive.google.com/thumbnail?id=1Cho8NxioEmcPaVy7O79gCeJYMB3kVmRm&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio", "Acero", "Ladrillo"], componentes: ["Muro transparente", "Estructura", "Carpinteria", "Piso", "Revestimiento", "Cubierta", "Parasol"], extra: ["Fachada modular", "Patio acuatico", "Fins hormigon"] },
      { src: "https://drive.google.com/thumbnail?id=1DcOSdhLbXX_BqE3wXGlNia7zPyhNWWef&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio", "Acero"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Barandilla", "Carpinteria", "Parasol", "Piso"], extra: ["fachada modular", "campanario hormigón", "colegio universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1t_YYKf3MS3Fhaf0ohMck04OIA50k1Tr3&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Cubierta", "Piso", "Estructura"], extra: ["Parasoles verticales", "Paisajismo escalonado", "Torreones de hormigón"] },
      { src: "https://drive.google.com/thumbnail?id=1k0sEYc-jEYJQTGp9Pg4jgVoENJqJXhfB&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Vidrio", "Hormigon", "Acero"], componentes: ["Muro transparente", "Muro opaco", "Carpinteria", "Piso", "Estructura"], extra: ["Fachada acristalada", "Composición modular", "Jardín formal"] },
      { src: "https://drive.google.com/thumbnail?id=1FAVVIHqlDpGfp6bgVrUVk961hOUW_ihK&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Cubierta", "Carpinteria", "Piso", "Revestimiento"], extra: ["fachada ritmica", "paisajismo minimalista", "colegio universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1Rlm5m_c32l-p4xWc8QuFQzRVQjBGnUxy&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Estar"],
        materiales: ["Madera", "Ladrillo", "Acero"], componentes: ["Muro opaco", "Cielorraso", "Piso", "Puerta", "Iluminacion", "Revestimiento", "Hogar"], extra: ["Mobiliario de autor", "Diseño escandinavo", "Interiorismo"] },
      { src: "https://drive.google.com/thumbnail?id=1e-OXfcHxlpEzyVY5YXguXNtqxCmx4UrB&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Plaza"],
        materiales: ["Hormigon"], componentes: ["Cubierta", "Piso", "Lucarna", "Aire acondicionado"], extra: ["Urbanismo paisajístico", "Patio circular", "Modulación"] },
      { src: "https://drive.google.com/thumbnail?id=1X6-BtCQMk015PFtDfaO9HWHZ1W5SrMOX&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Hormigon"], componentes: ["Muro opaco", "Cubierta", "Carpinteria", "Parasol"], extra: ["Colegio universitario", "Brise-soleil", "Paisaje integrado"] },
      { src: "https://drive.google.com/thumbnail?id=1DkPkOyGisgmUJLzXxApg64WIZcB1bnzI&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Estar"],
        materiales: ["Ladrillo", "Madera maciza", "Acero", "Vidrio"], componentes: ["Muro opaco", "Piso", "Cielorraso", "Hogar", "Iluminacion", "Carpinteria", "Puerta"], extra: ["Diseño de mobiliario", "Ladrillo visto", "Interiorismo modernista"] },
      { src: "https://drive.google.com/thumbnail?id=1jRvnda_FcBgruRaXE525ZmbfvgO5QZ24&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Madera maciza", "Ceramica"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Hogar", "Iluminacion", "Piso", "Carpinteria"], extra: ["Estructura vista", "Iluminacion lineal", "Mobiliario integrado"] },
      { src: "https://drive.google.com/thumbnail?id=1csN7zqHmtMKZaSO_QXw6-k6mqQeGFW9m&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de reuniones"],
        materiales: ["Hormigon", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion", "Carpinteria", "Parasol"], extra: ["Celosia exterior", "Hormigon visto", "Mesa conferencias"] },
      { src: "https://drive.google.com/thumbnail?id=1uFZgOtYCSabtmblilUDZR9UZuCnyk1nn&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de reuniones"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Carpinteria", "Persiana", "Lucarna"], extra: ["Brutalismo", "Luz cenital", "Encofrado visto"] },
      { src: "https://drive.google.com/thumbnail?id=1vtLLViooXEj9-pRY2MyQflwYWp_rriI7&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Estar"],
        materiales: ["Hormigon", "Vidrio", "Acero"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Cielorraso", "Iluminacion", "Parasol", "Estructura"], extra: ["Mobiliario iconico", "Luz natural", "Conexion exterior"] },
      { src: "https://drive.google.com/thumbnail?id=1FD4iWusYdmkIjnK2E_96_p0KRhSUb0db&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Estar"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Parasol"], extra: ["Mobiliario de autor", "Hormigon visto", "Integracion paisajistica"] },
      { src: "https://drive.google.com/thumbnail?id=1ZKVFYkX1izLqYiA0Kn19S9TnCpNOCkts&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza"], componentes: ["Estructura", "Muro opaco", "Revestimiento", "Cielorraso", "Piso", "Iluminacion"], extra: ["Mobiliario iconico", "Geometría modular", "Espacio institucional"] },
      { src: "https://drive.google.com/thumbnail?id=1BAM47mW_kum_iBuzOGUGDHYa1A60MILs&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Iluminacion"], extra: ["Comedor universitario", "Mobiliario de autor", "Retratos institucionales"] },
      { src: "https://drive.google.com/thumbnail?id=1dgCFjiXQVoEHjA-yyr7k_HnsVgqzqvgC&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Madera maciza", "Hormigon", "Ladrillo", "Vidrio", "Acero"], componentes: ["Muro opaco", "Cielorraso", "Estructura", "Iluminacion", "Carpinteria", "Muro transparente", "Piso"], extra: ["Mobiliario iconico", "Brutalismo interior", "Comedor colegial"] },
      { src: "https://drive.google.com/thumbnail?id=1FjgQLYiec80Sot9e6Y3xl2R6RZM3177L&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera laminada", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion", "Carpinteria", "Panel"], extra: ["Mobiliario icónico", "Vigas vistas", "Ladrillo visto"] },
      { src: "https://drive.google.com/thumbnail?id=1nXUcak4jvrLuuCG6jO5wzuUClKSyowBs&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Galeria"],
        materiales: ["Hormigon", "Madera maciza", "Ladrillo", "Acero"], componentes: ["Estructura", "Cielorraso", "Muro opaco", "Carpinteria", "Puerta", "Piso", "Manija"], extra: ["Paneleria madera", "Brutalismo", "Espacio transicional"] },
      { src: "https://drive.google.com/thumbnail?id=1EgscfIri6mJmp03K9Esc1ASN1bTRLWjv&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Madera laminada", "Acero", "Madera maciza", "Hormigon"], componentes: ["Piso", "Muro opaco", "Revestimiento"], extra: ["Silla Series 7", "Mobiliario integral", "Panelado de madera"] },
      { src: "https://drive.google.com/thumbnail?id=109Gi7DS5kKroCAYBhVdfqkZsa4KVEERD&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Madera laminada", "Hormigon", "Aluminio", "Acero", "Madera maciza"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Iluminacion", "Estructura", "Revestimiento"], extra: ["mobiliario de autor", "panelado de madera", "luz natural"] },
      { src: "https://drive.google.com/thumbnail?id=1xR2oJ3sqHwki8vf4GAn9cOHLe_jLXfzM&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Carpinteria", "Iluminacion", "Panel"], extra: ["Mobiliario Jacobsen", "Hormigón visto", "Panelado madera"] },
      { src: "https://drive.google.com/thumbnail?id=188XotgqbNzagFCxBzoDUCaPkO-ts90G2&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Auditorio"],
        materiales: ["Hormigon", "Madera laminada", "Acero"], componentes: ["Muro opaco", "Piso", "Carpinteria", "Barandilla", "Escalera", "Revestimiento"], extra: ["Gradas", "Hormigon visto", "Paneles acusticos"] },
      { src: "https://drive.google.com/thumbnail?id=1BBPftGJrpoATqlQcsT3cULrb5IQXszgt&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Auditorio"],
        materiales: ["Madera maciza", "Acero", "Vidrio", "Baldosa"], componentes: ["Revestimiento", "Cielorraso", "Muro opaco", "Piso", "Iluminacion", "Carpinteria", "Estructura"], extra: ["Sillas Jacobsen", "Aula magna", "Acustica"] },
      { src: "https://drive.google.com/thumbnail?id=1yiaSeTS6SP8Tyz48TDFiuxsv7DMAau-n&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Auditorio"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Barandilla", "Carpinteria", "Cielorraso", "Piso", "Iluminacion", "Panel", "Escalera"], extra: ["Auditorio escalonado", "Paneles acústicos", "Mobiliario Jacobsen"] },
      { src: "https://drive.google.com/thumbnail?id=1Gv1XzsmK6iiD_TiY5jiuqMwTKtS5CDRI&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Auditorio"],
        materiales: ["Hormigon", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Escalera", "Barandilla", "Iluminacion", "Carpinteria"], extra: ["Butacas escalonadas", "Paneles acusticos", "Iluminacion empotrada"] },
      { src: "https://drive.google.com/thumbnail?id=1yI5-EdUk-TF2sEK5hT-8QPWBiMvDT0YO&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Bronce", "Madera maciza", "Acero"], componentes: ["Iluminacion", "Muro transparente", "Calefaccion"], extra: ["Lámpara de escritorio", "Detalle interior", "Diseño de mobiliario"] },
      { src: "https://drive.google.com/thumbnail?id=1SsAvZMUftoZGtizc7GtWjxlyRKCbiS-f&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Madera maciza", "Vidrio", "Acero", "Bronce"], componentes: ["Piso", "Muro transparente", "Carpinteria", "Iluminacion", "Revestimiento"], extra: ["Escritorio integrado", "Iluminación puntual", "Conexión exterior"] },
      { src: "https://drive.google.com/thumbnail?id=1QzhGM642sllKx3DUrcSp6WpAefxID3FM&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Madera maciza", "Vidrio", "Acero"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Iluminacion"], extra: ["Mobiliario integrado", "Espacio de estudio", "Ventanal"] },
      { src: "https://drive.google.com/thumbnail?id=1JPk653j6Unf8v5kOzEW10thaTRHEWtgN&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Madera maciza", "Hormigon", "Acero", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Iluminacion", "Panel", "Estructura"], extra: ["Carrels", "Modularidad", "Luz natural"] },
      { src: "https://drive.google.com/thumbnail?id=1phCt4B4wxMvwx8-c9mtEcKlPH67d7tFH&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Hormigon", "Madera maciza", "Vidrio", "Acero"], componentes: ["Estructura", "Muro transparente", "Muro opaco", "Carpinteria", "Cielorraso", "Piso"], extra: ["Mobiliario integrado", "Composición modular", "Estilo escandinavo"] },
      { src: "https://drive.google.com/thumbnail?id=1LJC9xeN3YoIpQuFKNlYvIRa5wMzCVEh-&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Hormigon", "Vidrio", "Madera maciza", "Acero"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Iluminacion", "Panel", "Estructura"], extra: ["Ventana panorámica", "Mobiliario integrado", "Hormigón visto"] },
      { src: "https://drive.google.com/thumbnail?id=19Q61s7NGksm3wXpwVsit9OCWsfbOADYg&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Madera laminada", "Acero"], componentes: ["Piso", "Carpinteria", "Muro opaco"], extra: ["Sillas Swan", "Mobiliario diseño", "Estanterías"] },
      { src: "https://drive.google.com/thumbnail?id=1psyBMsk2Yd-kpdvXyIWGB8ETcXkGYFib&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Acero"], componentes: ["Cielorraso", "Piso", "Barandilla", "Muro opaco", "Entrepiso", "Iluminacion"], extra: ["Biblioteca universitaria", "Brutalismo", "Estanterías"] },
      { src: "https://drive.google.com/thumbnail?id=1SjX9GU7K20pgk_sl-0KSY1vR5cjr04Kr&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Madera maciza", "Hierro"], componentes: ["Muro opaco", "Cielorraso", "Piso", "Escalera", "Barandilla", "Iluminacion", "Panel"], extra: ["Brutalismo", "Estanterias", "Circulacion vertical"] },
      { src: "https://drive.google.com/thumbnail?id=1-tAaIZO3HNirp4JcTfT55a5nfpH3oJpP&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Barandilla", "Carpinteria", "Cielorraso", "Escalera", "Iluminacion", "Piso"], extra: ["Espacio multinivel", "Estanterías integradas", "Claroscuro"] },
      { src: "https://drive.google.com/thumbnail?id=1xFRg7woQRUFB9K2hNS_ZitNx-JoCFY0v&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Entrepiso", "Muro opaco", "Muro transparente", "Barandilla", "Carpinteria", "Cielorraso", "Escalera", "Iluminacion", "Piso"], extra: ["Hormigon visto", "Estanterias modulares", "Escalera caracol"] },
      { src: "https://drive.google.com/thumbnail?id=1PNbFuC21eXZApxpizmbMGEf_743sO9Hi&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza"], componentes: ["Estructura", "Entrepiso", "Muro opaco", "Cielorraso", "Piso", "Barandilla", "Iluminacion"], extra: ["doble altura", "luz tamizada", "pilares estructurales"] },
      { src: "https://drive.google.com/thumbnail?id=1U3ARGmTp9H5K1f5LhKpgaHnUt2WYjkvC&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Barandilla", "Cielorraso", "Iluminacion", "Piso", "Entrepiso"], extra: ["luz cenital", "doble altura", "biblioteca universitaria"] },
      { src: "https://drive.google.com/thumbnail?id=1K8FdY7ISYT9QuNZmuzt8k65cUxTph2lH&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Ladrillo", "Hormigon", "Acero", "Madera"], componentes: ["Estructura", "Entrepiso", "Muro opaco", "Barandilla", "Carpinteria", "Cielorraso", "Escalera", "Iluminacion", "Piso"], extra: ["Luz cenital", "Escalera caracol", "Entrepiso"] },
      { src: "https://drive.google.com/thumbnail?id=1qeOVVZimpe0ABludHe4OP3rXkZhtLOED&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Ladrillo", "Hormigon", "Madera maciza"], componentes: ["Muro opaco", "Cielorraso", "Piso", "Iluminacion", "Entrepiso", "Barandilla"], extra: ["Doble altura", "Mezzanine", "Mobiliario Jacobsen"] },
      { src: "https://drive.google.com/thumbnail?id=1WYnK3gZmmJKXYenUmTb78fwsT7crbWq-&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Madera maciza", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion", "Carpinteria"], extra: ["Luz cenital", "Espacio universitario", "Modernismo danes"] },
      { src: "https://drive.google.com/thumbnail?id=13IXHBrOUJ_T1G-Q9iif9mKYg3E4gMUCt&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Entrepiso", "Muro opaco", "Muro transparente", "Escalera", "Barandilla", "Cielorraso", "Piso", "Iluminacion", "Carpinteria"], extra: ["Biblioteca universitaria", "Escalera caracol", "Mobiliario iconico"] },
      { src: "https://drive.google.com/thumbnail?id=1MeSaxfsc6GawA_tnOQMJo32Dr4nYPg70&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Ladrillo", "Hormigon", "Madera", "Acero"], componentes: ["Muro opaco", "Cielorraso", "Piso", "Iluminacion"], extra: ["Sillas Swan", "Biblioteca universitaria", "Ladrillo visto"] },
      { src: "https://drive.google.com/thumbnail?id=18XIMlf5YwIiADBIbO_bvBiPfkOsTs8-v&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Madera maciza"], componentes: ["Escalera", "Barandilla", "Muro opaco", "Piso", "Cielorraso", "Iluminacion", "Carpinteria", "Puerta", "Estructura", "Panel", "Lucarna"], extra: ["Escalera helicoidal", "Iluminacion cenital", "Estanterias modulares"] },
      { src: "https://drive.google.com/thumbnail?id=1JpaBdz4_Gve8xoSMs0O3NsBFs0rcjFMl&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Entrepiso", "Muro opaco", "Muro transparente", "Escalera", "Barandilla", "Cielorraso", "Piso", "Iluminacion", "Revestimiento", "Carpinteria", "Panel"], extra: ["escalera caracol", "iluminacion colgante", "doble altura"] },
      { src: "https://drive.google.com/thumbnail?id=1VfeTVQ3u9rib-tcqooURt-DnLBesHAaV&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Hormigon", "Acero", "Ladrillo", "Madera", "Vidrio"], componentes: ["Estructura", "Cielorraso", "Piso", "Muro opaco", "Muro transparente", "Escalera", "Barandilla", "Iluminacion", "Carpinteria", "Panel"], extra: ["Escalera helicoidal", "Iluminación cenital", "Mobiliario Jacobsen"] },
      { src: "https://drive.google.com/thumbnail?id=1CVfGIT5baRF41CUtPpRu73bYmmxeUtoC&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Madera maciza", "Acero", "Vidrio", "Hormigon"], componentes: ["Iluminacion", "Piso", "Estructura", "Cielorraso", "Muro opaco"], extra: ["luminaria diseño", "mobiliario integrado", "espacio estudio"] },
      { src: "https://drive.google.com/thumbnail?id=1jO3K7uGwZFp7s4CQLFd2Md5WEekMrhUK&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Ladrillo", "Hormigon", "Madera maciza", "Acero"], componentes: ["Muro opaco", "Piso", "Cielorraso", "Iluminacion", "Estructura"], extra: ["Mobiliario iconico", "Ladrillo visto", "Iluminacion integrada"] },
      { src: "https://drive.google.com/thumbnail?id=1toWCq2yGjDGk1_8XhK3lytdc6mHhWgq6&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Ladrillo", "Madera maciza", "Acero", "Piedra", "Vidrio"], componentes: ["Muro opaco", "Piso", "Carpinteria", "Iluminacion", "Revestimiento"], extra: ["Mobiliario icónico", "Textil artístico", "Diseño escandinavo"] },
      { src: "https://drive.google.com/thumbnail?id=1twh7W9tBfVS-Ry__zbqSfbV2cYW98wob&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Iluminacion"], extra: ["brutalismo", "luz cenital", "columnata"] },
      { src: "https://drive.google.com/thumbnail?id=12U58z6fJOhCQLvoZly41e2odUBh6zeLY&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Sala de lectura"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Madera laminada", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion"], extra: ["Brutalismo", "Columnata", "Mobiliario integrado"] },
      { src: "https://drive.google.com/thumbnail?id=1J6VkMjN5PDL99li0vIS7MLV4I8anlFte&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Madera maciza"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Iluminacion", "Carpinteria"], extra: ["Iluminacion indirecta", "Ritmo espacial", "Mobiliario minimalista"] },
      { src: "https://drive.google.com/thumbnail?id=1V1GOLP-qf8vk01Q3m5nelP90d7jd_0nv&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Iluminacion", "Carpinteria", "Panel"], extra: ["Grand Hall", "Luz cenital", "Sillas Series 7"] },
      { src: "https://drive.google.com/thumbnail?id=1viv_t-aQnjjmFUCiOVfbPSy76wh0JN1x&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Iluminacion", "Puerta"], extra: ["Luz cenital", "Mobiliario integrado", "Grandes luces"] },
      { src: "https://drive.google.com/thumbnail?id=1GclcvLUaiiEVKG0UI0sd19PypwPZxLG-&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Lucarna", "Iluminacion"], extra: ["Comedor universitario", "Iluminacion cenital", "Brutalismo"] },
      { src: "https://drive.google.com/thumbnail?id=1v3VdBNQFBv7PXTvkvJYG8BW9fJNqOrV9&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Iluminacion", "Carpinteria"], extra: ["Refectorio", "Brutalismo", "Mobiliario iconico"] },
      { src: "https://drive.google.com/thumbnail?id=1XAtfwMYdSCr1Jy8Z2VBQg-mxB0FC6jg1&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Acero", "Piedra"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion"], extra: ["Comedor universitario", "Luz cenital", "Mobiliario diseñado"] },
      { src: "https://drive.google.com/thumbnail?id=1875zaOmDj7PH5nXCK28rYN8idQCS1YrU&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Iluminacion"], extra: ["Luz cenital", "Hormigon visto", "Celosia"] },
      { src: "https://drive.google.com/thumbnail?id=1VMTyxELY4rv_Yi6VREY6u2WkxYBecT9L&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Madera maciza", "Vidrio", "Ladrillo", "Piedra"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion", "Lucarna"], extra: ["Brutalismo", "Iluminacion cenital", "Mobiliario de autor"] },
      { src: "https://drive.google.com/thumbnail?id=1HNZ3AH6d3wYpOiTAmQfgxEQUKDd2GnbV&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio", "Acero"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Carpinteria", "Iluminacion", "Panel"], extra: ["Luz cenital", "Estructura vista", "Espacio columnado"] },
      { src: "https://drive.google.com/thumbnail?id=1HCGfnDDBVHDxZIPbI3prjMuB1NuSiveK&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion", "Panel"], extra: ["Iluminación cenital", "Hormigón visto", "Techo nervado"] },
      { src: "https://drive.google.com/thumbnail?id=1da2VszwfvwC29LPi_cYMraiilNmCtMV9&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio"], componentes: ["Muro opaco", "Estructura", "Cubierta", "Piso", "Carpinteria", "Barandilla", "Parasol"], extra: ["Campus", "Fachada modulada", "Patio central"] },
      { src: "https://drive.google.com/thumbnail?id=1DTlxDUXPpWIfK5oH_Qr4MjbluN4ndkbB&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Ladrillo", "Hormigon", "Madera maciza"], componentes: ["Muro opaco", "Estructura", "Cielorraso", "Piso", "Iluminacion", "Muro transparente"], extra: ["Brutalismo", "Iluminacion cenital", "Telas decorativas"] },
      { src: "https://drive.google.com/thumbnail?id=17WAdrFyRlo6n8gPCBaXlncYXUeMQfDrq&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Iluminacion"], extra: ["Refectorio", "Hormigón visto", "Mobiliario integrado"] },
      { src: "https://drive.google.com/thumbnail?id=18t5DStiGOc6214ASi4x69qA0EeOgCF6w&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Madera maciza", "Ladrillo", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion", "Carpinteria"], extra: ["mobiliario integrado", "iluminacion puntual", "comedor universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1oLBiafs2kr48b93hl-o-MeQJ6tM2-a2P&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Garaje cubierto"],
        materiales: ["Ladrillo", "Acero", "Vidrio", "Hormigon"], componentes: ["Muro opaco", "Muro transparente", "Cubierta", "Estructura", "Piso", "Iluminacion"], extra: ["Cicloparqueo", "Forma curva", "Pabellon"] },
      { src: "https://drive.google.com/thumbnail?id=18qBw15b21Ceu7boMj0Q_7DxEENTIczVo&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Escalera", "Barandilla", "Piso", "Cubierta"], extra: ["volumen articulado", "campus universitario", "diseno paisajistico"] },
      { src: "https://drive.google.com/thumbnail?id=1LpPUaiiDVFOwNMdjh1FXNDsj8YRboNXc&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Ladrillo", "Hormigon", "Acero", "Vidrio"], componentes: ["Muro opaco", "Revestimiento", "Carpinteria", "Puerta", "Barandilla", "Piso"], extra: ["Modularidad", "Arquitectura universitaria", "Retícula"] },
      { src: "https://drive.google.com/thumbnail?id=1KRIIJiWOE4NRvhJ6nBqGoQruaTggOatk&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio", "Acero"], componentes: ["Muro opaco", "Muro transparente", "Cubierta", "Carpinteria", "Piso", "Parasol"], extra: ["Modulación", "Ladrillo blanco", "Hormigón prefabricado"] },
      { src: "https://drive.google.com/thumbnail?id=19dfyysIx1GywYjxNmbBpExjt7pyN8yIb&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Cubierta", "Piso", "Iluminacion", "Instalacion pluvial", "Estructura"], extra: ["Piers", "Modulación", "Colegio"] },
      { src: "https://drive.google.com/thumbnail?id=121BtrTAo2GmgKh6xhR9dlJ3YpPYg3vRk&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Ladrillo", "Hormigon", "Acero", "Vidrio"], componentes: ["Muro opaco", "Estructura", "Cielorraso", "Piso", "Escalera", "Barandilla", "Iluminacion", "Carpinteria", "Entrepiso"], extra: ["Doble altura", "Ladrillo visto", "Silla Egg"] },
      { src: "https://drive.google.com/thumbnail?id=1ViKVXoWwfjYNdupwMXq3CcnogV20FJCp&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio", "Jardin"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio"], componentes: ["Muro opaco", "Cubierta", "Piso", "Carpinteria", "Canaleta"], extra: ["fachada ritmica", "patio colegial", "claristorio"] },
      { src: "https://drive.google.com/thumbnail?id=1VJTh_WoNVTdkW7dierakdDZlcEaJ5OSQ&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Ladrillo", "Vidrio", "Hormigon"], componentes: ["Muro opaco", "Muro transparente", "Carpinteria", "Cubierta", "Piso"], extra: ["Campus universitario", "Composicion modular", "Escultura"] },
      { src: "https://drive.google.com/thumbnail?id=11nRMQdAzXUuOVG1VV-hUS4jS6CUsMZVN&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Hormigon", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Puerta", "Cerco"], extra: ["Pergola", "Paseo ajardinado", "Modulacion"] },
      { src: "https://drive.google.com/thumbnail?id=1ji87mcUjYCb-6uM6opKFcJPPbWnQV63s&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Ladrillo", "Hormigon", "Acero", "Madera maciza", "Policarbonato"], componentes: ["Muro opaco", "Piso", "Cubierta", "Estructura", "Carpinteria", "Puerta", "Parasol", "Canaleta"], extra: ["Acceso principal", "Pergola", "Patron repetitivo"] },
      { src: "https://drive.google.com/thumbnail?id=1OhzZlEeoknTakCgzhL2S0QBvRKzErVFu&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Puerta", "Parasol"], extra: ["Brutalismo", "Pasarela cubierta", "Patio academico"] },
      { src: "https://drive.google.com/thumbnail?id=1OkcaCrg2IlV9ohybui2suWUV9qrvJkMC&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Piso", "Cubierta", "Parasol"], extra: ["modularidad", "hormigón visto", "serialidad"] },
      { src: "https://drive.google.com/thumbnail?id=1tutbzA_qGG3SrXyU5UfcReXzN2HTXZCL&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Aluminio", "Vidrio"], componentes: ["Estructura", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Cerco"], extra: ["Fachada modular", "Jardín formal", "Hormigón visto"] },
      { src: "https://drive.google.com/thumbnail?id=1WiLDOXZ7KuGbQY1pNIV_LvUMsp9VMviM&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Vereda"],
        materiales: ["Hormigon", "Ladrillo"], componentes: ["Muro opaco", "Piso", "Cubierta"], extra: ["Paisajismo formal", "Recorrido exterior", "Geometria simple"] },
      { src: "https://drive.google.com/thumbnail?id=1Pz_vLEY5PWiA2tkq_RkPq42u-M8pH8kz&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"],
        materiales: ["Hormigon", "Vidrio", "Acero", "Ladrillo"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Puerta", "Piso", "Iluminacion"], extra: ["Brutalismo", "Celosía", "Fachada acristalada"] },
      { src: "https://drive.google.com/thumbnail?id=1Z2iKuThoztULoJcTcBjfiXBk12luwY6-&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio"],
        materiales: ["Ladrillo", "Aluminio", "Hormigon", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Revestimiento"], extra: ["Fachada modular", "Diseño funcionalista", "Elementos prefabricados"] },
      { src: "https://drive.google.com/thumbnail?id=1YgkjN3Gb0YLc0ouf1rQCIo85vnUhMy_d&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Galeria"],
        materiales: ["Hormigon", "Acero"], componentes: ["Entrepiso", "Barandilla", "Parasol", "Estructura"], extra: ["brise-soleil", "hormigón visto", "circulación exterior"] },
      { src: "https://drive.google.com/thumbnail?id=1nBsYaAZZorwZ6jLSrAHP8FWk9V5xnUZF&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Acero"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Revestimiento"], extra: ["Hormigon visto", "Modulación de fachada", "Patio"] },
      { src: "https://drive.google.com/thumbnail?id=19FkoXS_fmQnhkFxsUL6khAewFF4oxTsh&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Cielorraso", "Piso"], extra: ["Arquitectura brutalista", "Quiebresol", "Paisajismo formal"] },
      { src: "https://drive.google.com/thumbnail?id=1AXqG4IeHBKcIhW8QIOxo9rN_fRggKauK&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio", "Acero", "Ladrillo", "Bronce"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Parasol", "Carpinteria", "Piso", "Revestimiento"], extra: ["Brutalismo", "Hormigon visto", "Celosia vertical"] },
      { src: "https://drive.google.com/thumbnail?id=1RQRG9JnoY-swVubgZvttfV2DNgUWWXK0&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Parasol", "Piso", "Revestimiento"], extra: ["Brutalismo", "Colonnata", "Campus universitario"] },
      { src: "https://drive.google.com/thumbnail?id=146Q6dVru1mj4ADpPC1oEteOUsZOsKfYn&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio", "Ladrillo"], componentes: ["Estructura", "Muro transparente", "Parasol", "Carpinteria", "Revestimiento", "Senaletica"], extra: ["Brutalismo", "Control solar", "Modulacion"] },
      { src: "https://drive.google.com/thumbnail?id=1z0X7z80nkS8QaTiVYtuDfNRbplzs3huO&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Patio", "Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Parasol", "Piso", "Carpinteria", "Revestimiento"], extra: ["Campus universitario", "Campanario", "Brutalismo"] },
      { src: "https://drive.google.com/thumbnail?id=1krXA721UUn15mDqdwSUCXkwf-8lVYTuJ&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Acero", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Carpinteria", "Parasol", "Piso", "Puerta", "Senaletica", "Cerco"], extra: ["Arquitectura brutalista", "Muro vegetal", "Celosia metalica"] },
      { src: "https://drive.google.com/thumbnail?id=1deCAWs1eD7H7bihnPSSOAIfJjePdN3f6&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Vidrio"], componentes: ["Muro opaco", "Carpinteria", "Piso", "Cubierta", "Parasol"], extra: ["Colegio universitario", "Patio", "Fachada panelada"] },
      { src: "https://drive.google.com/thumbnail?id=1xqqCpXG-qArguuonOwkID_2TZR2Gqfdd&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Parasol", "Carpinteria", "Piso", "Iluminacion"], extra: ["Hormigón visto", "Lamas", "Mampostería vista"] },
      { src: "https://drive.google.com/thumbnail?id=1-ZKoTURR9BVWWkU5xYs7-kqO2Ewwgm-z&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Acero", "Vidrio", "Piedra"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion"], extra: ["Claristorio", "Brutalismo", "Mobiliario diseñado"] },
      { src: "https://drive.google.com/thumbnail?id=1cHoZbNxZmeRthQMgjHwSMKcXkjJHM7pN&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Comedor"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Iluminacion"], extra: ["Brutalismo", "Refectorio", "Claristorio"] },
      { src: "https://drive.google.com/thumbnail?id=1oX68nUJVpPet0LFK0bIhOVSqNwmmQZRl&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Biblioteca"],
        materiales: ["Ladrillo", "Hormigon", "Madera maciza", "Acero", "Vidrio"], componentes: ["Muro opaco", "Cubierta", "Entrepiso", "Barandilla", "Carpinteria", "Cielorraso", "Lucarna", "Piso", "Iluminacion"], extra: ["Mobiliario iconico", "Doble altura", "Luz natural difusa"] },
      { src: "https://drive.google.com/thumbnail?id=1b4SjOBj1yHy1PAz8hvqqAfRXzwUyJRSQ&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Auditorio"],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion", "Carpinteria", "Barandilla", "Escalera", "Panel"], extra: ["Butacas", "Hormigón visto", "Revestimiento madera"] },
      { src: "https://drive.google.com/thumbnail?id=1EoIDYjof5RJGNhN9-iW3Tnd-0S1WhMUO&sz=w1600",
        escala: 7, tipografica: ["Planimetria"], tipoespacial: [],
        materiales: [], componentes: ["Muro opaco", "Carpinteria", "Escalera", "Piso"], extra: ["campus universitario", "trazado ortogonal", "plan maestro"] },
      { src: "https://drive.google.com/thumbnail?id=154pTfghwkaeb5EPq_-t8MGQ3PL9bEUF2&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: [],
        materiales: ["Hormigon", "Ladrillo", "Vidrio", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cubierta", "Parasol", "Carpinteria", "Revestimiento"], extra: ["Campanario", "Hormigon visto", "Brise-soleil"] },
      { src: "https://drive.google.com/thumbnail?id=1u23HFCdZyNXr2HByp_6Q95zfYK7243lk&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: [],
        materiales: ["Hormigon", "Vidrio"], componentes: ["Estructura", "Muro transparente", "Carpinteria", "Persiana", "Cielorraso"], extra: ["Muro cortina", "Hormigon visto", "Modulación"] },
      { src: "https://drive.google.com/thumbnail?id=1a5bTIrXwF11kKonU6ACUqOGLC_5LjfCz&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: [],
        materiales: ["Hormigon", "Ladrillo", "Baldosa", "Madera maciza", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Hogar", "Iluminacion", "Panel", "Barandilla"], extra: ["lounge hundido", "mobiliario Jacobsen", "vigas vistas"] },
      { src: "https://drive.google.com/thumbnail?id=1budh0kLJikbxZMm0hy2TI_X5bc_bVDpf&sz=w1600",
        escala: 11, tipografica: ["Vista"], tipoespacial: [],
        materiales: ["Acero", "Vidrio"], componentes: ["Muro transparente", "Carpinteria", "Muro opaco"], extra: ["Fachada modular", "Muro cortina", "Grilla de fachada"] },
      { src: "https://drive.google.com/thumbnail?id=1sC0iuWevEFdcG7xoDHIQWN3V6GTqSY__&sz=w1600",
        escala: 12, tipografica: ["Axonometria"], tipoespacial: [],
        materiales: ["Hormigon", "Vidrio"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Carpinteria", "Parasol", "Piso", "Rampa"], extra: ["Campus universitario", "Patio central", "Espejos de agua"] },
      { src: "https://drive.google.com/thumbnail?id=1Cxwg5qAfHbU7sfIn-fc0ZFe6zzACtRSf&sz=w1600",
        escala: 16, tipografica: ["Foto de maqueta"], tipoespacial: [],
        materiales: ["Madera maciza", "Vidrio"], componentes: ["Cubierta", "Muro opaco", "Muro transparente", "Piso", "Estructura"], extra: ["Maqueta volumetrica", "Diseno de campus", "Planeamiento urbano"] },
      { src: "https://drive.google.com/thumbnail?id=1J5bzGYfyo6wZ5zqA741b1CAFbr_m3RpT&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: [],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Piedra"], componentes: ["Estructura", "Muro opaco", "Cielorraso", "Piso", "Iluminacion"], extra: ["Refectorio", "Brutalismo", "Luz cenital"] },
      { src: "https://drive.google.com/thumbnail?id=1eJMGgmcHWyNaiLI2Ic2XBgzGFTPtqZQ9&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: [],
        materiales: ["Hormigon", "Ladrillo", "Madera maciza", "Acero"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Cielorraso", "Piso", "Iluminacion"], extra: ["Diseño mobiliario", "Luz cenital", "Comedor universitario"] },
      { src: "https://drive.google.com/thumbnail?id=1B7de9TlamZe-WtIhDSF4c_WXUazzkfSB&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: [],
        materiales: ["Ladrillo", "Hormigon", "Acero", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Barandilla", "Carpinteria", "Escalera", "Revestimiento", "Piso"], extra: ["Escalera exterior", "Ventanas corridas", "Fachada panelada"] },
      { src: "https://drive.google.com/thumbnail?id=1snHst0MHEXYNNxrUV4D_ayPP9MJRLQG1&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: [],
        materiales: ["Ladrillo", "Hormigon", "Vidrio"], componentes: ["Estructura", "Muro opaco", "Muro transparente", "Carpinteria", "Piso"], extra: ["Colegio universitario", "Patio ajardinado", "Modularidad"] },
      { src: "https://drive.google.com/thumbnail?id=1Z-NYzHO27zq-xNU2kO50vrwwjgIXZ9IE&sz=w1600",
        escala: 9, tipografica: ["Planta"], tipoespacial: [],
        materiales: [], componentes: ["Muro opaco", "Escalera", "Piso", "Patio"], extra: ["Plan maestro", "Grilla modular", "Patio central"] }
    ]
  },
{
    id: "lever-house",
    nombre: "Lever House",
    autor: "SOM — Gordon Bunshaft",
    estado: "Restaurado",
    uso: "Torre corporativa",
    pais: "USA",
    ciudad: "Nueva York",
    decada: "1950s",
    anio: "1952",
    fotografo: "Lucas Blair Simpson",
    complejidad: "Nivel 4",
    url: "https://www.metalocus.es/en/news/som-completes-restoration-lever-house-a-manhattan-office-icon-built-1952",
    cover: "https://drive.google.com/thumbnail?id=1LWa8CPd918Wxi-l8_Dn8akXCnZQmdd8d&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=16UBbtgQ9juBMpcO9wVyoZFENi-5YFkNP&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Lobby"],
        materiales: ["Marmol", "Vidrio", "Madera maciza"], componentes: ["Piso", "Muro transparente", "Cielorraso", "Iluminacion", "Barandilla", "Carpinteria", "Revestimiento"], extra: ["Planta libre", "Muro cortina", "Terraza exterior"] },
      { src: "https://drive.google.com/thumbnail?id=1zkbwWUQOc9nCVly8P8PpkY_h1ZguGlEw&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Lobby"],
        materiales: ["Vidrio", "Acero"], componentes: ["Estructura", "Muro transparente", "Cielorraso", "Piso", "Carpinteria"], extra: ["Curtain wall", "Pilotis", "Urban plaza"] },
      { src: "https://drive.google.com/thumbnail?id=13U69Pd6-xdTLzUWq4XNedKoOqzY075Dv&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Lobby"],
        materiales: ["Acero inoxidable", "Marmol", "Granito", "Vidrio", "Yeso"], componentes: ["Piso", "Cielorraso", "Iluminacion", "Muro opaco", "Ascensor", "Carpinteria", "Puerta", "Revestimiento", "Estructura"], extra: ["Lobby corporativo", "Acabados pulidos", "Circulacion vertical"] },
      { src: "https://drive.google.com/thumbnail?id=1JD-RB6h8eKx8ykTvex48cV5DL0Pj7kqX&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Lobby"],
        materiales: ["Vidrio", "Acero", "Granito", "Caliza", "Yeso"], componentes: ["Muro transparente", "Estructura", "Piso", "Cielorraso", "Iluminacion", "Puerta", "Revestimiento", "Carpinteria"], extra: ["Atrio", "Muro cortina", "Patio interior"] },
      { src: "https://drive.google.com/thumbnail?id=1oKvuzZtoq_ovNR8M-LpS_L8s3SCnWYdg&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso", "Vereda"],
        materiales: ["Vidrio", "Acero", "Marmol", "Granito", "Hormigon"], componentes: ["Muro transparente", "Estructura", "Carpinteria", "Piso", "Cielorraso", "Iluminacion", "Senaletica", "Puerta"], extra: ["Transparencia", "Lobby corporativo", "Pilar metalico"] },
      { src: "https://drive.google.com/thumbnail?id=13MOgIunuvidE0O-XBf9owBLWCzwaBWas&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Oficina", "Jardin", "Plaza"],
        materiales: ["Vidrio", "Acero", "Hormigon"], componentes: ["Estructura", "Muro transparente", "Piso", "Cielorraso", "Carpinteria"], extra: ["Pabellon elevado", "Cortina de vidrio", "Pilotis"] },
      { src: "https://drive.google.com/thumbnail?id=1LdHw4yJsZ98KszfI5Cid22W8i17QYxnJ&sz=w1600",
        escala: 15, tipografica: ["Render exterior"], tipoespacial: ["Oficina", "Calle"],
        materiales: ["Vidrio", "Acero"], componentes: ["Muro transparente", "Carpinteria", "Parasol", "Entrepiso", "Piso"], extra: ["Muro cortina", "Estilo Internacional", "Podio ajardinado"] },
      { src: "https://drive.google.com/thumbnail?id=1EZsLUC80qIWDGfa5y56TZq82z_yJCy4o&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"],
        materiales: ["Acero", "Vidrio", "Piedra"], componentes: ["Estructura", "Muro transparente", "Cielorraso", "Piso", "Iluminacion", "Revestimiento"], extra: ["Piloti", "Patio interior", "Fachada vidriada"] },
      { src: "https://drive.google.com/thumbnail?id=1zygebf0jGscw8wz-kJQBkK5zD07nZzae&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Calle"],
        materiales: ["Vidrio", "Acero", "Hormigon"], componentes: ["Estructura", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Parasol", "Entrepiso"], extra: ["Muro cortina", "Pilotis", "Plaza elevada"] },
      { src: "https://drive.google.com/thumbnail?id=1IcavUs1GkOKy4CoWgmh0-WCVDkRFS_Ry&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Vidrio", "Acero", "Hormigon", "PVC"], componentes: ["Muro transparente", "Carpinteria", "Piso", "Barandilla", "Parasol", "Iluminacion"], extra: ["Muro cortina", "Jardin en altura", "Patio interior"] }
    ]
  },
  {
    id: "refugio-delta",
    nombre: "Refugio en el Delta del Paraná",
    autor: "estudio mater",
    estado: "Construido",
    uso: "Refugio",
    pais: "Argentina",
    ciudad: "Delta del Paraná",
    decada: "2020s",
    anio: "2021",
    fotografo: "Sin crédito",
    complejidad: "Nivel 2",
    url: "https://www.instagram.com/p/DLFqP-nsrFU/",
    cover: "https://drive.google.com/thumbnail?id=1ROkyrDPghdDBRwDAzogorXrMypOSQqMJ&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=1ROkyrDPghdDBRwDAzogorXrMypOSQqMJ&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Acero", "Madera maciza", "Vidrio", "Hormigon"], componentes: ["Cubierta", "Estructura", "Muro transparente", "Piso", "Carpinteria", "Cielorraso", "Iluminacion"], extra: ["palafito", "elevado", "vegetacion"] },
      { src: "https://drive.google.com/thumbnail?id=1y_PgwsQAbTNb36b1JnfRGdxspLrdQwLp&sz=w1600",
        escala: 15, tipografica: ["Render exterior"], tipoespacial: ["Jardin"],
        materiales: ["Madera maciza", "Vidrio", "Hormigon", "Acero"], componentes: ["Estructura", "Cubierta", "Muro transparente", "Carpinteria", "Piso"], extra: ["palafito", "estructura madera", "tensores"] },
      { src: "https://drive.google.com/thumbnail?id=10psTYeR6WVElCrxEKETv9s_psyQolp15&sz=w1600",
        escala: 15, tipografica: ["Render interior"], tipoespacial: ["Comedor"],
        materiales: ["Madera maciza", "Vidrio"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Muro transparente", "Piso", "Cielorraso", "Carpinteria", "Panel"], extra: ["entorno natural", "ventilacion pasiva"] },
      { src: "https://drive.google.com/thumbnail?id=1Pxp8oniQvvhIGtfpsITcWy9nXmij4oyn&sz=w1600",
        escala: 15, tipografica: ["Render interior"], tipoespacial: ["Dormitorio"],
        materiales: ["Madera maciza", "Vidrio"], componentes: ["Estructura", "Cubierta", "Muro transparente", "Carpinteria", "Cielorraso", "Piso", "Persiana"], extra: ["Vistas al delta", "Ambiente natural"] },
      { src: "https://drive.google.com/thumbnail?id=1xQBjC4dyrNi1ilAgvj9TsyRFwPKdcyUw&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Acero", "Madera maciza"], componentes: ["Cubierta", "Estructura", "Barandilla", "Piso"], extra: ["Delta", "Refugio", "Paisaje fluvial"] },
      { src: "https://drive.google.com/thumbnail?id=1__Ek5NDk45ncDpMWndDIUMHYSzM1pcUZ&sz=w1600",
        escala: 16, tipografica: ["Foto de maqueta"], tipoespacial: ["Terraza"],
        materiales: ["Madera maciza", "Aluminio"], componentes: ["Estructura", "Cubierta", "Piso", "Escalera", "Barandilla", "Muro opaco"], extra: ["Palafito", "Estructura reticular"] },
      { src: "https://drive.google.com/thumbnail?id=1TOQ7j7t2LhaYpz5Yeuj9gICnkiIZnhcD&sz=w1600",
        escala: 16, tipografica: ["Foto de maqueta"], tipoespacial: ["Terraza"],
        materiales: ["Acero", "Madera maciza"], componentes: ["Estructura", "Cubierta", "Piso", "Escalera"], extra: ["Refugio", "Palafitico", "Delta"] },
      { src: "https://drive.google.com/thumbnail?id=12cB7j1Fj3qF0z7r-BWwwwde4f0wmyjqL&sz=w1600",
        escala: 16, tipografica: ["Foto de maqueta"], tipoespacial: ["Terraza"],
        materiales: ["Madera maciza", "Acero"], componentes: ["Estructura", "Cubierta", "Piso", "Escalera", "Barandilla"], extra: ["Palafitico", "Refugio", "Plataforma"] }
    ]
  },
  {
    id: "onix-saint-herblain",
    nombre: "ONIX",
    autor: "Atelier Jean Nouvel",
    estado: "Construido",
    uso: "Auditorio",
    pais: "Francia",
    ciudad: "Saint-Herblain",
    decada: "1980s",
    anio: "1988",
    fotografo: "Sin crédito",
    complejidad: "Nivel 4",
    url: "https://www.jeannouvel.com/en/projects/onyx/",
    cover: "https://drive.google.com/thumbnail?id=112NO1em7EtUrZKiok2GJyNOpKBu0rxZJ&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=12jHAEAwBs6aMBYww72lY1rdI_TQSIqo4&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Estacionamiento"],
        materiales: ["Acero", "Vidrio"], componentes: ["Muro opaco", "Muro transparente", "Piso", "Carpinteria", "Estructura", "Revestimiento"], extra: ["Marcas viales", "Edificio negro"] },
      { src: "https://drive.google.com/thumbnail?id=1bu0RMMPsKyL5RM0TFg_6Jc1KrAgKjVSe&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Estacionamiento"],
        materiales: ["Hormigon", "Acero"], componentes: ["Muro opaco", "Piso", "Iluminacion"], extra: ["Simetria", "Monolitico"] },
      { src: "https://drive.google.com/thumbnail?id=1JGqu2iNNfmKs-4StNHf4z3shka7ZlrC6&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Calle"],
        materiales: ["Acero", "Policarbonato"], componentes: ["Estructura", "Revestimiento", "Muro translucido", "Iluminacion", "Piso"], extra: ["Estelas de luz", "Fachada perforada"] },
      { src: "https://drive.google.com/thumbnail?id=10XmRmiOvKMEp7TXyN8CdmDLXB3VfIAkU&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Estacionamiento"],
        materiales: ["Acero", "Vidrio"], componentes: ["Revestimiento", "Muro transparente", "Carpinteria", "Escalera", "Barandilla"], extra: ["Paneles perforados", "Reflejos"] },
      { src: "https://drive.google.com/thumbnail?id=1E_IPSczIAa7QXXfpKH_My-jD_Fq0YRyx&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"],
        materiales: ["Acero", "Vidrio"], componentes: ["Estructura", "Muro translucido", "Muro transparente", "Escalera", "Barandilla", "Iluminacion", "Revestimiento"], extra: ["Celosia metalica", "Reflejos"] },
      { src: "https://drive.google.com/thumbnail?id=1J_KkY_8cXXkIyZ4u6zpdxKt6IGyPwmdv&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Auditorio"],
        materiales: ["Acero"], componentes: ["Estructura", "Cubierta", "Cielorraso", "Muro opaco", "Escalera", "Iluminacion", "Piso", "Barandilla", "Panel", "Carpinteria"], extra: ["butacas", "iluminacion escenica"] },
      { src: "https://drive.google.com/thumbnail?id=1g6qpe8LQIm0LD2T2vWXwr_HoR9RO5y0_&sz=w1600",
        escala: 4, tipografica: [], tipoespacial: ["Hall de ingreso"],
        materiales: ["Hormigon", "Madera maciza", "Acero", "Vidrio"], componentes: ["Cielorraso", "Piso", "Muro opaco", "Muro transparente", "Escalera", "Barandilla", "Iluminacion", "Carpinteria", "Panel"], extra: ["Iluminacion ambiente", "Madera oscura"] },
      { src: "https://drive.google.com/thumbnail?id=112NO1em7EtUrZKiok2GJyNOpKBu0rxZJ&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Calle"],
        materiales: ["Hormigon", "Acero", "Tierra compactada"], componentes: ["Estructura", "Muro opaco", "Piso", "Iluminacion", "Revestimiento"], extra: ["Reflejo agua", "Fachada negra"] }
    ]
  },
  {
    id: "border-crossing-anapra",
    nombre: "Border Crossing Anapra",
    autor: "Office KGDVS",
    estado: "No construido",
    uso: "Infraestructura",
    pais: "Mexico",
    ciudad: "Anapra",
    decada: "2000s",
    anio: "2005",
    fotografo: "Sin crédito",
    complejidad: "Nivel 5",
    url: "https://officekgdvs.com/projects/15",
    cover: "https://drive.google.com/thumbnail?id=1uN_3BDqcvNBEtYfxDe1N5SZTTRtCDmhD&sz=w1600",
    imagenes: [
      { src: "https://drive.google.com/thumbnail?id=1dPpB_ASe9T6zsng1O5jSvW83Y9nsvPYD&sz=w1600",
        escala: 15, tipografica: ["Render exterior"], tipoespacial: ["Calle"],
        materiales: ["Hormigon", "Acero"], componentes: ["Muro opaco", "Puerta", "Cerco", "Cubierta"], extra: ["Desierto", "Muro monumental", "Palmeras"] },
      { src: "https://drive.google.com/thumbnail?id=1ClSI1KQ2IyuXZ09dyJZNiStcIUJgXIA8&sz=w1600",
        escala: 3, tipografica: [], tipoespacial: ["Jardin"],
        materiales: ["Hormigon", "Tierra compactada"], componentes: ["Estructura", "Cubierta", "Muro opaco", "Cerco", "Piso"], extra: ["Cubierta verde", "Desierto", "Arquitectura enterrada"] },
      { src: "https://drive.google.com/thumbnail?id=1tuMrC-sNbK5Xwj6CnfgWkmoovTLj60eL&sz=w1600",
        escala: 9, tipografica: ["Planta"], tipoespacial: [],
        materiales: [], componentes: ["Muro opaco", "Estructura", "Escalera", "Ascensor"], extra: ["estructura reticular", "circulacion"] }
    ]
  }
];
